import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generatePdfInvoice({ company, name, phone, gst, address, selectedProductIds, products, itemQuantities, packInfo }) {
  const compName = company || 'Valued Customer';
  const custName = name || 'Wholesale Buyer';
  const custPhone = phone || 'N/A';
  const delAddress = address || 'Standard Delivery';

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // 1. Header & Brand Banner
  doc.setFillColor(1, 3, 86); // Royal Navy (#010356)
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('GOVINDASAMY & CO', 15, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Quality Mat & Textile Products Manufacturer & Wholesaler', 15, 25);
  doc.text('Email: govindasamy.textitle@gmail.com | Phone: +91 98429 32756', 15, 30);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('PURCHASE ORDER INVOICE', 130, 20);

  // 2. Customer Details Box
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('CUSTOMER & BILL-TO DETAILS:', 15, 45);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Company Name: ${compName}`, 15, 52);
  doc.text(`Contact Person: ${custName}`, 15, 58);
  doc.text(`Phone / WhatsApp: ${custPhone}`, 15, 64);
  if (gst) doc.text(`GSTIN: ${gst}`, 15, 70);

  const splitAddress = doc.splitTextToSize(`Delivery Address: ${delAddress}`, 100);
  doc.text(splitAddress, 15, gst ? 76 : 70);

  const today = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFont('helvetica', 'bold');
  doc.text(`Order Date: ${today}`, 130, 45);
  doc.text(`Order Ref: GSC-ORD-${Date.now().toString().slice(-6)}`, 130, 52);
  doc.text(`Master Shipping Bales: ${packInfo.estPacks} Bales`, 130, 58);

  // 3. Itemized Table Data
  const tableData = [];
  let grandTotal = 0;
  let index = 1;

  selectedProductIds.forEach((id) => {
    const prod = products.find((p) => p.id === id);
    const qty = itemQuantities[id] || 1;
    if (prod) {
      const subtotal = prod.baseRate * qty;
      grandTotal += subtotal;
      const pcsInfo = prod.bundlePieces > 0 ? ` (${qty * prod.bundlePieces} pcs)` : '';

      tableData.push([
        index.toString(),
        `${prod.title} [${prod.category}]`,
        `${qty} ${prod.unit.replace('per ', '')}s${pcsInfo}`,
        `Rs. ${prod.baseRate.toLocaleString('en-IN')}`,
        `Rs. ${subtotal.toLocaleString('en-IN')}`
      ]);
      index++;
    }
  });

  // 4. Render Table
  autoTable(doc, {
    startY: 85,
    head: [['S.No', 'Product Description', 'Quantity / Pack', 'Unit Rate', 'Subtotal Amount']],
    body: tableData,
    headStyles: {
      fillColor: [1, 3, 86],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      font: 'helvetica'
    },
    columnStyles: {
      0: { cellWidth: 15, halign: 'center' },
      1: { cellWidth: 80 },
      2: { cellWidth: 35, halign: 'center' },
      3: { cellWidth: 30, halign: 'right' },
      4: { cellWidth: 30, halign: 'right' }
    }
  });

  let finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : 130;
  if (finalY > 240) {
    doc.addPage();
    finalY = 20;
  }

  // 5. Total Calculation Summary Box
  doc.setFillColor(248, 250, 252);
  doc.rect(110, finalY, 85, 24, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(110, finalY, 85, 24, 'D');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Est. Master Bales: ${packInfo.estPacks} Bales`, 115, finalY + 8);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(1, 3, 86);
  doc.text('GRAND TOTAL:', 115, finalY + 17);

  doc.setTextColor(37, 132, 2); // Emerald Green
  doc.setFontSize(13);
  doc.text(`Rs. ${grandTotal.toLocaleString('en-IN')}`, 155, finalY + 17);

  // 6. Footer Notes
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Note: This is an automated Order Inquiry Invoice generated by Govindasamy & Co.', 15, finalY + 32);
  doc.text('Please share this PDF or order details to WhatsApp: +91 98429 32756 for payment & lorry transport confirmation.', 15, finalY + 37);

  const cleanFileName = compName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`Govindasamy_Mat_Order_${cleanFileName}.pdf`);
}
